// Generated by Selenium IDE
package jenkins.plugins.testlink.examples;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class USERTESTLINKTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void uSERTESTLINK() {
    driver.get("http://172.16.4.13/testlink/login.php?note=logout&viewer=");
    driver.manage().window().setSize(new Dimension(1272, 676));
    driver.findElement(By.id("tl_login")).click();
    driver.findElement(By.id("tl_login")).sendKeys("Rafik");
    driver.findElement(By.id("tl_login")).click();
    driver.findElement(By.id("tl_password")).click();
    driver.findElement(By.id("tl_password")).sendKeys("499084");
    driver.findElement(By.cssSelector(".form__field:nth-child(7) > input")).click();
  }
}
